root = "." 
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "tmp/main"  # The location where the compiled binary will be stored
  cmd = "go build -o tmp/main ./cmd/api"  # Corrected build command
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "docs"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[screen]
  clear_on_rebuild = false
  keep_scroll = true
